### ISSUE TITLE
Tutorial or tool for compiling mods for webXash

### ISSUE THREAD

**Issue by Dakedres** [x8BitRain/webXash#6]
It would be nice if there was a tutorial, or even a npm script for compiling mods.

This is an issue I had with Xash3D, and the absolutely messy repo didn't make trying to figure it out on my own any easier.

Thank you for reviving this project

**Comment by x8BitRain** [comment]
@Dakedres I've updated the readme, I should have had this guide there from the start, thanks for reminding me.

https://github.com/x8BitRain/webXash/blob/main/README.md#running-mods
