### ISSUE TITLE
Error while trying to load the map "rocket_frenzy"

### ISSUE THREAD

**Issue by TheDeafenGuy** [x8BitRain/webXash#8]
I loaded up my copy of the full version of HL, and I try to load the map "rocket_frenzy" via the multiplayer menu. When I attempt to, the game freezes and gives me the error:
"Xash Error

ED_AllocEdict: no free edicts".

Could this error be because this is an older version of xash?

**Comment by x8BitRain** [comment]
Yes, this uses a much older version of Xash3d [compiled in 2017](https://github.com/FWGS/xash3d/blob/master/ports/README.emscripten.md), so far there is no easy way to compile the current xash3D-FWGS into WASM unfortunately
